### ISSUE TITLE
Create new instance function

### ISSUE THREAD

**Issue by arjan123** [martijndeh/fire#1]
Request:

It would be great if there was a function that create an instance of a model including including all the properties with default values, calculated fields aso. 

(maybe such a function is already there?)

ps. I'm studying on the code at the moment...

**Comment by martijndeh** [comment]
In `0.41.0` we introduced a `ModelInstance#new` method. This creates a new model instance without persisting it to the datastore. When calling `ModelInstance#save` on the object it'll persist to the datastore.

The below creates a `Pie` instance and saves it to the datastore:
```
var pie = helper.app.models.Pie.new();
pie.type = 'Apple';
pie.save()
```

`ModelInstance#new` is isomorphic so it's available on both the front- and the back-end.
