### ISSUE TITLE
Different id name in model?

### ISSUE THREAD

**Issue by van-nguyen** [martijndeh/fire#13]
Hi there, I'm having trouble creating a model with a different name for the id primary key field.

Is this just how the ORM works? And I can't do something like:

``` javascript
this.id = undefined;
this.other_id = [this.Id];
```

Cheers.

**Comment by martijndeh** [comment]
Ah yes I'm afraid `id` is hardcoded as primary key at several locations in the code at the moment. There are some comments/todos to replace it with a `.getPrimaryKey()` method instead.

To prevent the `id` from being created automatically, I think you can do something like:
```js
function User() {
    // Setting the id property as empty array will prevent the property from being created.
    this.id = [];
    this.otherId = [this.UUID, this.CanUpdate(false)];
}
```

But a lot of things will stop working, like associations, the API, and probably some more parts. What do you want to achieve? You don't like `id` as primary key?

**Comment by van-nguyen** [comment]
That's fine, I kinda like the abstraction, but having the flexibility is nice though. I was writing an import script and needed some hacks with renaming all primary key fields as "id" from the data source I was using.. namely the itunes data feed https://www.apple.com/itunes/affiliates/resources/documentation/itunes-enterprise-partner-feed.html

**Comment by martijndeh** [comment]
This issue is not relevant anymore. Please have a look at the new version.
