### ISSUE TITLE
Move migrations functionality to separate module

### ISSUE THREAD

**Issue by airtonix** [martijndeh/fire#16]
Automatically creating new migrations based on model changes is what every node developer coming from Django has been looking for.

**Comment by martijndeh** [comment]
There isn't much development in Node on Fire anymore. I should put up a notice in the README.

I think your best bet is to have a look at https://github.com/locomote/node-migrate-orm2, or http://docs.sequelizejs.com/en/v3/docs/migrations/. The migrations aren't auto-generated like in Node on Fire and Django, but it should be possible to implement in one of these projects.

I myself prefer to use https://github.com/martijndeh/lego nowadays. It avoids another abstraction like an ORM and still makes it fairly easy to change models (alter tables), but you do need to write SQL.
