### ISSUE TITLE
apps:create problem

### ISSUE THREAD

**Issue by mgwmgw** [martijndeh/fire#6]
I had installed npm, fire, and postgresql and pgadmin3 on an RHEL6 virtual machine,
and then rebooted just to make sure.
Then I tried to create my first app:
fire apps:create helloworld

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
Why does this fail?  Thanks.

**Comment by martijndeh** [comment]
I just published a beta release which adds additional logs.

Could you install the beta release `npm install fire@0.41.1 -g`, run `DEBUG=fire:* fire apps:create helloworld` and let me know the result? Thanks!

**Comment by martijndeh** [comment]
`0.42.0` is the latest stable release which should fix several onboarding issues. Could you `npm install fire -g` and try again?

**Comment by javajenks** [comment]
Just tried with 0.42.3 - something still seems broken..

C:\Users\jjenkins>npm install -g fire
C:\Users\jjenkins\AppData\Roaming\npm\fire -> C:\Users\jjenkins\AppData\Roaming\
npm\node_modules\fire\bin\cli.js
fire@0.42.3 C:\Users\jjenkins\AppData\Roaming\npm\node_modules\fire


C:\Users\jjenkins>fire apps:create linview
.write(string, encoding, offset, length) is deprecated. Use write(string[, offse
t[, length]][, encoding]) instead.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn C:\Users\jjenkins\AppData\Roaming\npm\node_modules\fire\node_module
s\.bin\bower ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

**Comment by martijndeh** [comment]
It looks like the path to `bower` is invalid. Do you have `bower` installed globally?

**Comment by javajenks** [comment]
Bower looks good..

**Comment by martijndeh** [comment]
In `fire apps:create ...` Node on Fire executes `bower` to install it's dependencies.

I just release `fire@0.43.0` which adds a `--global-bower` option to `fire apps:create`. Can you try to install this version and create an app with the `--global-bower` option please?

`npm install fire@0.43.0 -g`
`fire apps:create linview --global-bower`

Hopefully this works. In the mean time I'll debug the issue on a Windows machine. Could you run the following line and let me know what it outputs please? `node -e "console.log(require('path').join(__dirname, '..', 'node_modules', '.bin', 'bower'))"`

Thanks!

**Comment by javajenks** [comment]
Installed 0.43.0 - but still the same error. Here's the output you requested.

`C:\Users\jjenkins>node -e "console.log(require('path').join(__dirname, '..', 'no
de_modules', '.bin', 'bower'))"
..\node_modules\.bin\bower`

**Comment by martijndeh** [comment]
OK, `0.42.4` is available which fixes onboarding on Windows. I've tested this on a Windows VM.

There were some issues with the paths on Windows. Specially, starting paths with a `.` doesn't work on Windows. Additionally, in some situations, commands need to be postfixed with `.cmd` to be able to run when spawning another process. This should all be fixed now.

Can you please `npm install fire@0.42.4 -g` and `fire apps:create test` to confirm?

**Comment by javajenks** [comment]
Looking great now :fire: :+1:
