### ISSUE TITLE
Error creating "schemas" relation when running 'grunt release' for multi-apps example

### ISSUE THREAD

**Issue by kierer** [martijndeh/fire#9]
When trying to run the 'fire release' step for the multi-apps example, I get the following error:

> fire release
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn node_modules/.bin/grunt ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

Then, if I try to use 'grunt release' straight off, I see:

>grunt release
Running "release:migrate" (release) task
relation "schemas" does not exist
error: relation "schemas" does not exist
    at Connection.parseE (/home/kierer/dev/fire/examples/multiple-apps/node_modules/fire/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/home/kierer/dev/fire/examples/multiple-apps/node_modules/fire/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/home/kierer/dev/fire/examples/multiple-apps/node_modules/fire/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
Fatal error: relation "schemas" does not exist

I initially thought it might be a case issue brought on by the quoting of the relation name on creation, but I checked the example source and case is consistent for "schemas"; I see that there was a similar issue that was resolved going into 0.28.2, however.

**Comment by martijndeh** [comment]
I've updated the example project. You were not doing anything wrong. It was using an old version of the framework.

Can you pull and try again? Please let me know how it goes!

The TodoMVC is also a nice example project. Have you looked at that one? It does use bower, so please do a `bower install` too. In future versions we're moving away from bower though.

**Comment by kierer** [comment]
Thank you (and thanks for sharing a very cool project)! TodoMVC is very nice- it worked straight away. I really want to get all of the examples working toward better exploring the framework. Although I still got the above errors in multi-apps after updating, I found was able to make them go away by consolidating the migrations for the multi-apps example into a single '001.js' file and putting that under the app2 migrations folder prior to running 'fire release', so the problem seems to be related to the use of multiple migration files (start with a blank database to reproduce). Also, I just tried the 'isomorphic' example and although the 'fire build' and 'fire release' steps succeed, 'fire run' fails with 

Warning: Task "run" not found. Use --force to continue.
Aborted due to warnings.

It's probably something simple- I'll jump in to take a look after exploring the migration code a bit more deeply toward trying to understand what was happening with multi-apps.

I saw the move to browserify in the develop branch- very nice!

**Comment by martijndeh** [comment]
I think the error you're seeing in the multiple apps example is related to the shared models. In a project with multiple apps, one app is configured as the master app. This means the migrations of shared models, such as Schema, are created and invoked in the master app. The Schema model (which is the schemas relation you see in your error) is required when running the release (migrate). This means if you try to release the non-master app, which is app2, before you release the master app, which is app1, you'll receive an error.

Can you confirm this by... `fire config:set NODE_APP=app1` and try `fire release`? Then `fire config:set NODE_APP=app2` and `fire release`? Does that work in that order?

Tip: you can also quickly create a new datastore in postgres by invoking `fire datastore:create databasename`. This command also automatically sets your `DATABASE_URL`.

Not too sure what's going on with the isomorphic example. Did you do an `npm install` and does the `node_modules` folder exist?

I'm glad to hear you find it a cool project! There is some more good stuff coming like the Streams (web sockets plus LISTEN and NOTIFY in Postgres) and the Search module which introduces `Model#search` (easy full text search backed by Postgres).

If you want to contribute to Node on Fire in anyway, help improving and spreading the word you're super welcome. ;-)

**Comment by kierer** [comment]
Thank you- that was it on the multi-app front; it was always starting out with NODE_APP set to app2! I really need to roll up my sleeves and dig into the code more deeply this weekend; I should have caught that. I had done `npm install` and `node_modules` was present with the isomorphic example, so something else is going on; I'll poke around a bit more and post once I get it working.

You bet- I already started spreading the word a bit! A friend and teammate of mine who has a good deal of experience coding similar stacks is looking forward to checking the project out when he returns from vacation next week; I mentioned to him that I think there may be pretty good alignment between the Node of Fire goals and how we've been approaching things- it would be great to be able to contribute. Thanks again!
